#!/usr/bin/env bash

rofi_args="-normal-window -theme ~/.config/rofi/global/rofi.rasi"

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]/%.gpg/$'\n'}" )
password_files=( "${password_files[@]% }" )
password_files="$(echo "${password_files[@]}" | sed 's/ //g' | sed '/\..*\// s/\(.*\)\/\(.*\)/\1\/\2CHANGEME1iconCHANGEME2\/\/home\/platinumBamboo\/\.cache\/favicons\/\1\.ico/')"
password_files="${password_files//CHANGEME1/'\0'}"
password_files="${password_files//CHANGEME2/'\x1f'}"

password=$(echo -e "$password_files" | rofi $rofi_args -dmenu -show-icons)

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
